FROM rocker/tidyverse:4.1.2

RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libpython3-dev \
  python3-pip \
  && install2.r \
    --deps TRUE \
    reticulate \
	fivethirtyeight
